# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d66e382b6f305dedaccd8ce0d39c3b4799c04cedc21e5d0a6a502e60c9175914b5fc57fc99a10266f2659daf7ff97431adbc5ab23f72ae641cceaab9ee3e09ed

test:
  secret_key_base: f642ea50ecea72a80f69f4e5368c079b147166a446e474b5db3b5b6e7ed7170d74f3c22527a86aaca5de8dd974d7d027e6caca3b00fc95ee68da87a084a1321c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
